/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "smart_city_esp8266.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smartcity_devices_DiscoveryRequest, smartcity_devices_DiscoveryRequest, AUTO)


PB_BIND(smartcity_devices_DeviceInfo, smartcity_devices_DeviceInfo, AUTO)


PB_BIND(smartcity_devices_DeviceInfo_CapabilitiesEntry, smartcity_devices_DeviceInfo_CapabilitiesEntry, AUTO)


PB_BIND(smartcity_devices_DeviceUpdate, smartcity_devices_DeviceUpdate, AUTO)


PB_BIND(smartcity_devices_TemperatureHumidityData, smartcity_devices_TemperatureHumidityData, AUTO)


PB_BIND(smartcity_devices_AirQualityData, smartcity_devices_AirQualityData, AUTO)


PB_BIND(smartcity_devices_CurrentSensorData, smartcity_devices_CurrentSensorData, AUTO)


PB_BIND(smartcity_devices_CameraData, smartcity_devices_CameraData, AUTO)


PB_BIND(smartcity_devices_ACIRStatus, smartcity_devices_ACIRStatus, AUTO)


PB_BIND(smartcity_devices_DeviceCommand, smartcity_devices_DeviceCommand, AUTO)


PB_BIND(smartcity_devices_ClientRequest, smartcity_devices_ClientRequest, AUTO)


PB_BIND(smartcity_devices_GatewayResponse, smartcity_devices_GatewayResponse, AUTO)











#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

